---
- name: Build GoldenAMI
  #hosts filter used when coming from a provision template
  hosts: "{{ hosts_filter_windows | default('all') }}"
  gather_facts: true

  tasks:
  
  - name: create ami
    action: 
      module: ec2_ami
      instance_id: i-07233a3e0ed225f25
      region: ap-southeast-2
      state: present
      description: AMI created as golden image
      name: goldenAMI-"{{ ansible_date_time.epoch }}"
      wait: yes
    register: goldenAMI
