---
- name: Build GoldenAMI
  #hosts filter used when coming from a provision template
  hosts: localhost
  gather_facts: true

  tasks:

  - name: print out AMI Name
    debug:
      msg: goldenAMI-{{ ansible_date_time.epoch }}
  
  - name: create ami
    action: 
      module: ec2_ami
      instance_id: i-07233a3e0ed225f25
      region: ap-southeast-2
      state: present
      description: AMI created as golden image
      name: goldenAMI-{{ ansible_date_time.epoch }}
      wait: yes
    register: goldenAMI
