- name: Push SNS MSG
  hosts: localhost
  
  tasks:
  - name: Send message via SNS Topic
    sns:
      msg: "Message"
      subject: "Subject"
      topic: "arn:aws:sns:ap-southeast-2:239048922879:notifyuser"
    delegate_to: localhost