- name: Push SNS MSG
  hosts: localhost
  
  tasks:
  - name: Send message via SNS Topic
    sns:
      msg: "{{ sns_msg }}"
      subject: "{{ sns_subject }}"
      topic: "arn:aws:sns:ap-southeast-2:239048922879:notifyuser"
      region: ap-southeast-2
    delegate_to: localhost